### PR TITLE
Fix-level-not-found

### PR DESCRIPTION
**Pull request by anthonie-kramer**
Updates:
* Fixed issue with level not found by assigning default / dummy values until a level is created. The warning message still appears when a level is deleted after spaces have been created on it.
* Added feature for inside out workflow that cuts the profile of an added space from an auto generated space. This will no longer happen once the auto generated space is edited (and becomes an override)

Testing:
* The function has been staged, and can be tested in this workflow (Space Planning Template -> Draw from Scratch):
https://hypar.io/workflows/a8be8103-aa2a-469c-a9c1-a2ad9f9074f1?view=2588d205-bcad-4236-a4d8-0b875911ec16

Things to test:
1. Drawing spaces before Floor / Levels are created
2. Creating a Floor / Level after drawing
3. Spaces will cut their profiles out of an autogenerated space
4. Multiple levels works as intended (including copy / paste from level below)

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
This looks good, barring a few minor comments below. Let's hold on merging this until we can test it with the migrations work @cdriesler is doing; he's making quick progress, so we should be able to give this a serious test next week :crossed_fingers: 

> Reviewed 16 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-:-NfRK5NP-6uXShdPUmjT:bly7z9j)* status: 1 change requests, 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @anthonie-kramer)

___
*[`src/SpacePlanning.cs` line 3 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-NfRH_NhDbeCQ8zPW_o1:-NfRH_NhDbeCQ8zPW_o2:b-ejr0on) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/33d7b90ccb06e0c1ff599ef22e5e244a7834b705/src/SpacePlanning.cs#L3)):*
> ```Smalltalk
> using Elements;
> using Elements.Geometry;
> using Namotion.Reflection;
> ```

Is this import being used? 
___
*[`src/SpacePlanning.cs` line 492 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-NfRHdam3ObA4LV7HKLu:-NfRHdam3ObA4LV7HKLv:b-fw0e8q) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/33d7b90ccb06e0c1ff599ef22e5e244a7834b705/src/SpacePlanning.cs#L492)):*
> ```Smalltalk
>         /// <param name="floorsModel">The floors model, which may or may not exist</param>
>         /// <param name="lvl">The level volume</param>
>         // private static void AdjustLevelVolumesToFloors(Model floorsModel, LevelVolume lvl)
> ```

If we don't need this anymore, let's just delete it. But let's also make sure that spaces seem to size their heights correctly relative to floors in the model.

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @anthonie-kramer)

___
*[`dependencies/SpaceBoundary.cs` line 323 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-NfRKboR609t78A7kWeC:-NfRKboR609t78A7kWeD:b-44byzi) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/33d7b90ccb06e0c1ff599ef22e5e244a7834b705/dependencies/SpaceBoundary.cs#L323)):*
> ```Smalltalk
>             var matchingLevelLayout = new LevelLayout();
> 
>             if (levelLayouts.Count == 0 || levelLayouts[0].Name.Contains("dummy"))
> ```

This check refers to the name "dummy" but we also removed the setting of the name "dummy-level-volume" above. Is this a backwards compatibility thing?

**Review by anthonie-kramer — COMMENTED** [review]
Sounds good! I have a couple updates after responding to your comments

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-:-NfY0t3V4Qw08Txp_2P1:b417wki)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @andrewheumann)

___
*[`dependencies/SpaceBoundary.cs` line 323 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-NfRKboR609t78A7kWeC:-NfXyVwO-AiKaYres6sY:b-ut5e0a) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/33d7b90ccb06e0c1ff599ef22e5e244a7834b705/dependencies/SpaceBoundary.cs#L323)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

This check refers to the name "dummy" but we also removed the setting of the name "dummy-level-volume" above. Is this a backwards compatibility thing?
</blockquote></details>

Yeah, you're right, we can remove these checks now... We will find out if we need it when we do migrations tests :)
___
*[`src/SpacePlanning.cs` line 3 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-NfRH_NhDbeCQ8zPW_o1:-NfY-lxf-2PACxwElNw0:b-t4lrhy) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/33d7b90ccb06e0c1ff599ef22e5e244a7834b705/src/SpacePlanning.cs#L3)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

Is this import being used?
</blockquote></details>

No, I'm not sure what it's from....
___
*[`src/SpacePlanning.cs` line 492 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-NfRHdam3ObA4LV7HKLu:-NfY0-o255d7gyqyOUdu:b-xqd679) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/33d7b90ccb06e0c1ff599ef22e5e244a7834b705/src/SpacePlanning.cs#L492)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

If we don't need this anymore, let's just delete it. But let's also make sure that spaces seem to size their heights correctly relative to floors in the model.
</blockquote></details>

Yeah, the spaces have heights based on the level volume, which is currently the shortest of all similar level volumes when merging them... We can probably do something more clever in the future like looking for profiles in the next level up and then extruding portions of the space based on the heights (for instance if a space is at the location of a step in elevation for levels above). I have some commented code that does something similar, but haven't added yet because it messes up view scopes (bbox is based on vertices of representations)

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Looks good. We'll aim to get this tested and released next week! 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-:-Ng3RRYfChPCJSzf0YV2:bi5g7nk)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

___
*[`dependencies/SpaceBoundary.cs` line 72 at r2](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-Ng3R5lJ29KjZh09s4jD:-Ng3R5lJ29KjZh09s4jE:b-uivca) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/f1ba42b74ea0e25e58955629d18636d8787fb5ed/dependencies/SpaceBoundary.cs#L72)):*
> ```Smalltalk
>             foreach (var kvp in Requirements)
>             {
>                 var color = kvp.Value.Color; // ?? Colors.Aqua; // this shouldn't ever actually be null, but just in case...
> ```

Does commenting this out not give you a compile error after `hypar init`? I think because of recent cli changes `Color` is always `nullable...

**Review by andrewheumann — COMMENTED** [review]
I've started a bit of manual testing in anticipation of the migrations work. Here is a random customer workflow I grabbed. There is a subtle change when switching to the `test` version reflecting this code — one of the pantries goes away: (before/diff/after)


> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-:-Ng8pihbEcV2V4_wKQ3u:beazkkw)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

___
*[`dependencies/SpaceBoundary.cs` line 72 at r2](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-Ng3R5lJ29KjZh09s4jD:-Ng9GmtB4MID1Z8kdFWM:bt3p5pb) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/f1ba42b74ea0e25e58955629d18636d8787fb5ed/dependencies/SpaceBoundary.cs#L72)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

Does commenting this out not give you a compile error after `hypar init`? I think because of recent cli changes `Color` is always `nullable...
</blockquote></details>

ah, it's related to elements / hypar version. If you point `dependencies` to the latest alphas of elements/functions, you need to add this back in.

**Review by anthonie-kramer — COMMENTED** [review]
Interesting... do you have the workflow? I can investigate.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-:-NgJsOx_Eibgm5S3BADs:b-mkodro)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @andrewheumann)

___
*[`dependencies/SpaceBoundary.cs` line 72 at r2](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-Ng3R5lJ29KjZh09s4jD:-NgJtldy-Ltrt25_fich:b43fun0) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/f1ba42b74ea0e25e58955629d18636d8787fb5ed/dependencies/SpaceBoundary.cs#L72)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

ah, it's related to elements / hypar version. If you point `dependencies` to the latest alphas of elements/functions, you need to add this back in.
</blockquote></details>

This is `Color` from `ProgramRequrement` ... did this change recently?

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Oh sorry I meant to link it! https://hypar.io/workflows/ad796ff4-ddc9-492b-a1d3-c643afb9a65f

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-:-NgOJ6LU8LcXPyPUo3Z8:b-z6fyp6)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

___
*[`dependencies/SpaceBoundary.cs` line 72 at r2](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-Ng3R5lJ29KjZh09s4jD:-NgOJ9-lBkZxHpGFKvIs:bf27xoa) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/f1ba42b74ea0e25e58955629d18636d8787fb5ed/dependencies/SpaceBoundary.cs#L72)):*
<details><summary><i>Previously, anthonie-kramer (Anthonie Kramer) wrote…</i></summary><blockquote>

This is `Color` from `ProgramRequrement` ... did this change recently?

</blockquote></details>

yes, this change: https://github.com/hypar-io/Elements/pull/1011 — I think what ultimately matters though is the CLI version you're using, which will codegen this differently to be a `Color?`

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @andrewheumann)

___
*[`dependencies/SpaceBoundary.cs` line 72 at r2](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/9#-Ng3R5lJ29KjZh09s4jD:-NgU9odVBNWUxF-R8-rV:b-5z8g2l) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/f1ba42b74ea0e25e58955629d18636d8787fb5ed/dependencies/SpaceBoundary.cs#L72)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

yes, this change: https://github.com/hypar-io/Elements/pull/1011 — I think what ultimately matters though is the CLI version you're using, which will codegen this differently to be a `Color?`
</blockquote></details>

You're right, I had to update to the latest alpha version

**Pull request merged**
