### PR TITLE
fix creating space on wrong level

### PR DESCRIPTION
**Pull request by KaterynaSloboda**
- Stop comparing levels by AddId if this property is null in the override

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1)

### CODE REVIEW

**Review by serenayl — CHANGES_REQUESTED** [review]
Awesome, this works great and I've published it! Small config thing blocking below.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1#-:-NXCdFRQ9_aAFq6-vlge:b-dzt8x6)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @KaterynaSloboda)

___
*[`dependencies/SpacePlanning.Dependencies.csproj` line 16 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1#-NXCd0qCEiS3Qw96joti:-NXCd0qCEiS3Qw96jotj:bgpympn) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/341e2b855a6d87ab3fe1fa934665facdf3ba9390/dependencies/SpacePlanning.Dependencies.csproj#L16)):*
> ```XML
>     <ProjectReference
>       Include="..\..\HyparSpace\LayoutFunctions\LayoutFunctionCommon\LayoutFunctionCommon.csproj" />
>     <ProjectReference Include="..\..\Elements\Elements\src\Elements.csproj" />
> ```

Can we undo these changes before merge? For some reason my init and build works great with the specified 2.0.0-alphal.12 but has conflicts with local elements.



_Code quote:_
```XML
    <!-- <PackageReference Include="Hypar.Elements" Version="2.0.0-alpha.12" /> -->
    <PackageReference Include="Hypar.Functions" Version="1.6.0" />
    <!-- <PackageReference Include="Hypar.Space.LayoutFunctionCommon" Version="1.4.0" /> -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DebugHelper\DebugHelper.csproj" />
    <ProjectReference
      Include="..\..\HyparSpace\LayoutFunctions\LayoutFunctionCommon\LayoutFunctionCommon.csproj" />
    <ProjectReference Include="..\..\Elements\Elements\src\Elements.csproj" />
```

**Comment by KaterynaSloboda** [comment]
> Awesome, this works great and I've published it! Small config thing blocking below.
> 
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1#-:-NXCdFRQ9_aAFq6-vlge:b-dzt8x6)_ status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @KaterynaSloboda)
> 
> _[`dependencies/SpacePlanning.Dependencies.csproj` line 16 at r1](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1#-NXCd0qCEiS3Qw96joti:-NXCd0qCEiS3Qw96jotj:bgpympn) ([raw file](https://github.com/hypar-io/Function-SpacePlanning/blob/341e2b855a6d87ab3fe1fa934665facdf3ba9390/dependencies/SpacePlanning.Dependencies.csproj#L16)):_
> 
> > ```
> >     <ProjectReference
> >       Include="..\..\HyparSpace\LayoutFunctions\LayoutFunctionCommon\LayoutFunctionCommon.csproj" />
> >     <ProjectReference Include="..\..\Elements\Elements\src\Elements.csproj" />
> > ```
> 
> Can we undo these changes before merge? For some reason my init and build works great with the specified 2.0.0-alphal.12 but has conflicts with local elements.
> 
> _Code quote:_
> 
> ```
>     
>     <PackageReference Include="Hypar.Functions" Version="1.6.0" />
>     
>     <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
>   </ItemGroup>
>   <ItemGroup>
>     <ProjectReference Include="..\..\DebugHelper\DebugHelper.csproj" />
>     <ProjectReference
>       Include="..\..\HyparSpace\LayoutFunctions\LayoutFunctionCommon\LayoutFunctionCommon.csproj" />
>     <ProjectReference Include="..\..\Elements\Elements\src\Elements.csproj" />
> ```

Done

**Review by serenayl — COMMENTED** [review]
Approving and staged but holding off on publishing until after the conference/training.

> Reviewed 1 of 1 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1#-:-NXvelFtDzIDr3sKUg6_:bc1nfol)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion

**Review by serenayl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1#-:-NXvergy3c3vpVZCYICd:bnfp4nl)* status: 1 of 1 approvals obtained, 1 unresolved discussion

**Review by serenayl — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/Function-SpacePlanning/1)* status: 1 of 1 approvals obtained, 1 unresolved discussion

**Pull request merged**
